name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./StreamSphere/client

      # Build frontend (React + Vite)
      - name: Build frontend
        run: npm run build
        working-directory: ./StreamSphere/client

      # (Optional) Install backend dependencies
      # This step is useful if you later convert server to Azure Functions
      - name: Install backend dependencies
        run: npm install
        working-directory: ./StreamSphere/server

      # Deploy to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_BUSH_0F856D710 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### IMPORTANT PATHS ######
          app_location: "./StreamSphere/client"   # React app
          api_location: "./StreamSphere/server"   # Express backend (must be Azure Functions)
          output_location: "dist"                 # Vite build output

  # Job to handle pull request close
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_BUSH_0F856D710 }}
          action: "close"
